CONTAINER AWDSkeletonAnimationTag
{
	NAME AWDSkeletonAnimationTag;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BOOL AWDSKELETON_EXPORT{}
		STRING AWDSKELETON_NAME { }
		LONG AWDSKELETON_EXPORTRANGE
		{
			CYCLE
			{
				AWDSKELETON_RANGEGLOBAL;
				AWDSKELETON_RANGEDOC;
				AWDSKELETON_RANGEPREV;
				AWDSKELETON_RANGECUSTOM;
			}
		}
		LONG AWDSKELETON_FIRSTFRAME {MIN 1; MAX 50;  FIT_H; SCALE_H; }
		LONG AWDSKELETON_LASTFRAME {MIN 1; MAX 50;  FIT_H; SCALE_H;}


	}
}
