#ifndef _AWDSkeletonAnimationTag_H_
#define _AWDSkeletonAnimationTag_H_

enum
{		
			
	AWDSKELETON_EXPORT  	= 1010,
	AWDSKELETON_NAME  		= 1011,
	AWDSKELETON_EXPORTRANGE  	= 1012,
	AWDSKELETON_FIRSTFRAME  	= 1013,
	AWDSKELETON_LASTFRAME  		= 1014,
	AWDSKELETON_RANGEGLOBAL  	= 1015,
	AWDSKELETON_RANGEDOC  		= 1016,
	AWDSKELETON_RANGEPREV  		= 1017,
	AWDSKELETON_RANGECUSTOM  	= 1018,
};

#endif
