CONTAINER AWDObjectSettings
{
	NAME AWDObjectSettings;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BOOL DAPE_EXPORT{}
		BOOL DAPE_APPLYTOCHILDS{}
		GROUP DAPE_OBJECTSETTINGS
		{
			COLUMNS 1;
			BOOL DAPE_LIGHTS {}
			BOOL DAPE_UV {}
			BOOL DAPE_NORMALS {}
			BOOL DAPE_TRIANGULATE {}
			BOOL DAPE_OPTIMIZE {}
		LONG DAPE_TOOL
		{
			CYCLE
			{
				DAPE_MOVE;
				DAPE_ROTATE;
				DAPE_COMBOID;
			}
		}
		LONG DAPE_TOOL_ANIMATION
		{
			CYCLE
			{
				DAPE_NOANIMATION;
				DAPE_ANIMATION;
				DAPE_ANIMATIONONLY;
			}
		}
		LONG DAPE_TOOLID {MIN 0; MAX 99999999999; FIT_H; SCALE_H;}
		}
		}	
	}
}
